### PR TITLE
fix(.env.example): change 0.0.0.0 to localhost to allow ipv6

### PR DESCRIPTION
**Pull request by mnzaki**
The default of 0.0.0.0 for `HOST` can cause issues on machines that have IPV6 configured, as typically localhost is bound to ::1 and when a listening socket is opened it automatically listens on the IPV4 address 127.0.0.1.
This causes an issue for example if another application tries to access the strapi server as "localhost:1337" which will get resolved to the IPV6 ::1 but strapi isn't listening :(

### CODE REVIEW

**Comment by derrickmehaffy** [comment]
Yeah it's a known issue on Macs since Apple in their inf wisdom changed localhost to use the ipv6 localhost by default

**Comment by mnzaki** [comment]
Well it's also an issue on my Arch linux with ipv6, mdns6, tailscaled and systemd-networkd... gotta support ipv6 at some point :P

**Comment by derrickmehaffy** [comment]
> Well it's also an issue on my Arch linux with ipv6, mdns6, tailscaled and systemd-networkd... gotta support ipv6 at some point :P

I agree for local networks but within a LAN (especially localhost) using the ipv4 format should still be the default.

**Review by PaulBratslavsky — APPROVED** [review]
Thanks Derrick and mnzaki

**Pull request merged**
