### PR TITLE
adding possibility to create new pages on strapi without changeing frontend

### PR DESCRIPTION
**Pull request by KennyAtCodin**
Please review and let me know if it works for you :)

### CODE REVIEW

**Comment by PaulBratslavsky** [comment]
@KennyAtCodin will review later this week.  Thank you for the PR.

**Comment by PaulBratslavsky** [comment]
@KennyAtCodin thanks for the PR will merge today.

@diramazioni I will look at your fix as well, in terms of the metadata not being present, I think there might be a bug that was introduced in the SEO plugin.  I will take a look at that.

**Comment by diramazioni** [comment]
@PaulBratslavsky I had configure the SEO plugin for the Page then it works.
However I find it rather confusing to  have a metadata component and the SEO component, Which one is better and internationalized?

**Comment by KennyAtCodin** [comment]
@diramazioni: I suggest using the SEO component, it has a nice preview feature. Internationalized are both, because of the way strapi handles internationalization. There is an open PR https://github.com/strapi/nextjs-corporate-starter/issues/32 I didn't had the chance to get to this yet. Maybe if you have time you could implement this.

**Pull request merged**
