### PR TITLE
Update post.tsx

### PR DESCRIPTION
**Pull request by adarsh-jha1611**
In this updated code, a new property tags is added to the Article interface. The tags property is an array of strings representing the tags associated with the article. Within the Post component, a new section is added to display the tags. The tags are rendered as <span> elements with appropriate styling. The tags are looped over using map() function, and each tag is displayed within a <span> element.

### CODE REVIEW

**Comment by PaulBratslavsky** [comment]
@adarsh-jha1611 in order to complete this PR we need to reflect these changes in the backend as well.  

It can function similar to how `Category` is implemented already.

You can see these images as reference and create something similar for `tags` contentType

**Comment by adarsh-jha1611** [comment]
> @adarsh-jha1611 in order to complete this PR we need to reflect these changes in the backend as well.
> 
> It can function similar to how `Category` is implemented already.
> 
> You can see these images as reference and create something similar for `tags` contentType
> 
> 
> 
> 

Sure i'll update you over this

**Comment by PaulBratslavsky** [comment]
I am going to close this for now, unless you would like to revisit the topic.

**Comment by PaulBratslavsky** [comment]
@adarsh-jha1611 I am going to close this for now, until you would like to revisit this and add the appropriate changes in the Strapi admin.  Thank you.

**Pull request closed without merging**
